parameters:
- name: environment
  type: string
- name: subscriptionEndpoint
  type: string

jobs:
- deployment: deploy_adf
  displayName: 'Deploy to Azure Data Factory'
  pool:
    vmImage: 'windows-2019'
  variables:
    packageWheelName: 'none'
  environment: ${{ parameters.environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        # - checkout: mdwdataops_adfpublish
        #   path: 'adf_publish' 

        # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell
        # - task: AzurePowerShell@4
        #   inputs:
        #     azureSubscription: ${{ parameters.subscriptionEndpoint }}
        #     ScriptPath: '$(Pipeline.Workspace)/ciartifacts/adf_scripts/deploymentadf.ps1'
        #     ScriptArguments: '-armTemplate "$(Pipeline.Workspace)\adf_publish\$(devAdfName)\ARMTemplateForFactory.json" -ResourceGroupName "$(rgName)" -DataFactoryName "$(adfName)" -predeployment $true'
        #     azurePowerShellVersion: LatestVersion
        #   displayName: 'Azure PowerShell script: Stop ADF triggers'

        # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment
        - task: AzureResourceGroupDeployment@2
          displayName: 'Azure Deployment:Create Or Update Resource Group action on $(rgName)'
          inputs:
            azureSubscription: ${{ parameters.subscriptionEndpoint }}
            resourceGroupName: '$(rgName)'
            location: '$(azureLocation)'
            csmFile: '$(Pipeline.Workspace)/adf_publish/$(devAdfName)/ARMTemplateForFactory.json'
            csmParametersFile: '$(Pipeline.Workspace)/adf_publish/$(devAdfName)/ARMTemplateParametersForFactory.json'
            overrideParameters: -factoryName "$(adfName)" -AzureBlobStorage1_properties_typeProperties_serviceEndpoint "https://$(persistentStorage).blob.core.windows.net"


        # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell
        # - task: AzurePowerShell@4
        #   displayName: 'Azure PowerShell script: Start ADF triggers'
        #   inputs:
        #     azureSubscription: ${{ parameters.subscriptionEndpoint }}
        #     ScriptPath: '$(Pipeline.Workspace)/ciartifacts/adf_scripts/deploymentadf.ps1'
        #     ScriptArguments: '-armTemplate "$(Pipeline.Workspace)\adf_publish\$(devAdfName)\ARMTemplateForFactory.json" -ResourceGroupName "$(rgName)" -DataFactoryName "$(adfName)" -predeployment $false'
        #     azurePowerShellVersion: LatestVersion



